steps:
  - name: gcr.io/cloud-builders/gcloud
  - id: list instances
  - args:
      - compute
      - instances
      - list
      - -- PROJECT=searce-playground
# steps:
#   - name: gcr.io/cloud-builders/gcloud
#   - id: create image
#   - args:
#     - compute 
#     - images 
#     - create 
#     - IMAGE_NAME 
#     - --source-disk=GCE_INSTANCE_NAME
#     - --source-disk-zone=ZONE --project PROJECT'
#     env:
#       - 'IMAGE_NAME = mig-update-image'              
#       - 'GCE_INSTANCE_NAME = rahulprajapati-instance-1'            
#       - 'ZONE = asia-east1-b'                           
#       - 'PROJECT = searce-playground' 

#   - name: gcr.io/cloud-builders/gcloud
#   - id: create instance template

#   - args:
#     - compute -
#     - -project=PROJECT_ID 
#     - instance-templates 
#     - create 
#     - INSTANCE_TEMPLATE_NAME 
#     - --machine-type=MACHINE_TYPE 
#     - --subnet=projects/PROJECT_ID/regions/REGION/subnetworks/SUBNETWORK 
#     - --no-address 
#     - --maintenance-policy=MIGRATE 
#     - --service-account=SERVICE_ACCOUNT 
#     - --scopes=https://www.googleapis.com/auth/cloud-platform 
#     - --region=REGION 
#     - --tags=TAGS 
#     - --image=IMAGE_NAME 
#     - --image-project=IMAGE_PROJECT_ID 
#     - --boot-disk-size=30GB 
#     - --boot-disk-type=pd-balanced 
#     - --boot-disk-device-name=INSTANCE_TEMPLATE_NAME 
#     - --no-shielded-secure-boot 
#     - --shielded-vtpm 
#     - --shielded-integrity-monitoring 
#     - --reservation-affinity=any'
#     env:
#       - 'PROJECT = searce-playground'
#       - 'INSTANCE_TEMPLATE_NAME = mig-template-launch'
#       - 'MACHINE_TYPE = e2-micro'
#       - 'SUBNETWORK = rahulprajapati-subnet-1'                   
#       - 'REGION = asia-east1'
#       - 'SERVICE_ACCOUNT = rahulprajapati-mig-pipeline-ac@searce-playground.iam.gserviceaccount.com'
#       - 'TAGS = http-server,https-server'
#       - 'IMAGE_NAME = mig-update-image'  
#       - 'IMAGE_PROJECT_ID = searce-playground'


#   - name: gcr.io/cloud-builders/gcloud
#   - id: update instance template
#   - args:
#     - compute 
#     - instance-groups 
#     - managed 
#     - rolling-action 
#     - start-update 
#     - MIG_NAME 
#     - --version=template=INSTANCE_TEMPLATE_NAME 
#     - --type=proactive 
#     - --zone=ZONE 
#     - --project=PROJECT_ID'
#     env:
#       - 'MIG_NAME = mig-rahul-jenkins-testing'
#       - 'INSTANCE_TEMPLATE_NAME = mig-template-launch'
#       - 'ZONE = sia-east1-b'
#       - 'PROJECT_ID = searce-playground'
