steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - compute
      - images
      - create
      - ${_IMAGE_NAME}
      - '--source-disk=${_GCE_INSTANCE__NAME}'
      - '--source-disk-zone=${_ZONE}'
      - '--project=${_PROJECT}'
    id: create image
    
    
  - name: gcr.io/cloud-builders/gcloud
    id: create instance template
    args:
     - compute 
     - --project=${_PROJECT_ID}
     - instance-templates 
     - create 
     - ${_INSTANCE_TEMPLATE_NAME}
     - --machine-type=${_MACHINE_TYPE}
     - --subnet=projects/${_PROJECT_ID}/regions/${_REGION}/subnetworks/${_SUBNETWORK}
     - --no-address 
     - --maintenance-policy=MIGRATE 
     - --service-account=${_SERVICE_ACCOUNT}
     - --scopes=https://www.googleapis.com/auth/cloud-platform 
     - --region=${_REGION}
     - --tags=${_TAGS}
     - --image=${_IMAGE_NAME}
     - --image-project=${_IMAGE_PROJECT_ID}
     - --boot-disk-size=30GB 
     - --boot-disk-type=pd-balanced 
     - --boot-disk-device-name=${_INSTANCE_TEMPLATE_NAME}
     - --no-shielded-secure-boot 
     - --shielded-vtpm 
     - --shielded-integrity-monitoring 
     - --reservation-affinity=any

  - name: gcr.io/cloud-builders/gcloud
    id: update instance template
    args:
    - compute 
    - instance-groups 
    - managed 
    - rolling-action 
    - start-update 
    - ${_MIG_NAME}
    - --version=template=${_INSTANCE_TEMPLATE_NAME}
    - --type=proactive 
    - --zone=${_ZONE}
    - --project=${_PROJECT_ID}

substitutions:
    _IMAGE_NAME: mig-update-image11
    _GCE_INSTANCE__NAME: rahulprajapati-instance-1
    _ZONE: asia-east1-b
    _PROJECT: searce-playground
    _PROJECT_ID: searce-playground
    _INSTANCE_TEMPLATE_NAME: mig-template-launch11
    _MACHINE_TYPE: e2-micro
    _SUBNETWORK: rahulprajapati-subnet-1
    _REGION: asia-east1
    _SERVICE_ACCOUNT: rahulprajapati-mig-pipeline-ac@searce-playground.iam.gserviceaccount.com
    _TAGS: http-server,https-server
    _IMAGE_PROJECT_ID: searce-playground
    _MIG_NAME: mig-rahul-jenkins-testing
